# Generated by Django 3.0.4 on 2020-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistimages',
            name='user',
            field=models.TextField(default='Surya Vamshi'),
        ),
    ]
